/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.27.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type ExecuteMsg = {
  change_admin: {
    new_admin: Addr;
  };
} | {
  change_fees: {
    new_fees: FeeStructure;
  };
} | {
  receive: Cw20ReceiveMsg;
};
export type Addr = string;
export type Uint128 = string;
export type Binary = string;
export interface FeeStructure {
  basic_arch_id_cost: Uint128;
  basic_partner_cost: Uint128;
  dao_base_cost: Uint128;
  devenue_control_cost: Uint128;
  pay_token_addr: Addr;
  premium_arch_id_cost: Uint128;
  premium_partner_cost: Uint128;
  royalty_customization_cost: Uint128;
  [k: string]: unknown;
}
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
  [k: string]: unknown;
}
export interface InstantiateMsg {
  admin: Addr;
  dao_core_code_id: number;
  fees: FeeStructure;
}
export type QueryMsg = {
  query_fees: {};
} | {
  query_plan: {
    dao_addr: Addr;
  };
} | {
  query_upgrade: {
    dao_addr: Addr;
    new_plan: Plan;
  };
};
export type Timestamp = Uint64;
export type Uint64 = string;
export type ArchIDLevel = "n_a" | "basic" | "premium";
export type PartnerLevel = "n_a" | "basic" | "premium";
export interface Plan {
  next_pay: Timestamp;
  tier: Tier;
  [k: string]: unknown;
}
export interface Tier {
  arch_id_lvl: ArchIDLevel;
  custom_royalties: boolean;
  devenue_control: boolean;
  partner_lvl: PartnerLevel;
  [k: string]: unknown;
}