/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.27.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type ExecuteMsg = {
  receive: Cw20ReceiveMsg;
} | {
  receive_nft: Cw721ReceiveMsg;
} | {
  purchase_native: {
    collection: string;
    token_id: string;
    [k: string]: unknown;
  };
} | {
  remove_listing: {
    collection: string;
    token_id: string;
    [k: string]: unknown;
  };
};
export type Uint128 = string;
export type Binary = string;
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
  [k: string]: unknown;
}
export interface Cw721ReceiveMsg {
  msg: Binary;
  sender: string;
  token_id: string;
  [k: string]: unknown;
}
export interface InstantiateMsg {
  admin_fee: Fee;
  credit_contract: string;
  native_denom: string;
  [k: string]: unknown;
}
export interface Fee {
  decimal_places: number;
  rate: number;
  recipient: string;
  [k: string]: unknown;
}
export type QueryMsg = {
  cw721_deposits: {
    collection: string;
    owner: string;
    [k: string]: unknown;
  };
} | {
  ask: {
    collection: string;
    token_id: string;
    [k: string]: unknown;
  };
} | {
  get_all_asks: {
    [k: string]: unknown;
  };
} | {
  get_collection_asks: {
    collection: string;
    [k: string]: unknown;
  };
};
export interface Ask {
  collection: string;
  cw20_contract?: string | null;
  price: Uint128;
  seller: string;
  token_id: string;
  [k: string]: unknown;
}
export type Cw20HookMsg = {
  purchase: {
    cw721_contract: string;
    token_id: string;
    [k: string]: unknown;
  };
};
export type Cw721HookMsg = {
  set_listing: {
    amount: number;
    cw20_contract?: string | null;
    [k: string]: unknown;
  };
};