/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.27.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { Uint128, Ask, Cw20HookMsg, Cw721HookMsg, ExecuteMsg, Binary, Cw20ReceiveMsg, Cw721ReceiveMsg, Fee, InstantiateMsg, QueryMsg, Uint64, Volume } from "./Marketplace.types";
export interface MarketplaceReadOnlyInterface {
  contractAddress: string;
  ask: ({
    collection,
    tokenId
  }: {
    collection: string;
    tokenId: string;
  }) => Promise<AskResponse>;
  getAllAsks: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: Uint64;
  }) => Promise<GetAllAsksResponse>;
  getSellerAsks: ({
    seller
  }: {
    seller: string;
  }) => Promise<GetSellerAsksResponse>;
  getCollectionAsks: ({
    collection
  }: {
    collection: string;
  }) => Promise<GetCollectionAsksResponse>;
  getCollectionVolume: ({
    collection
  }: {
    collection: string;
  }) => Promise<GetCollectionVolumeResponse>;
  collectionDossier: ({
    collection
  }: {
    collection: string;
  }) => Promise<CollectionDossierResponse>;
  batchCollectionDossier: ({
    collections
  }: {
    collections: string[];
  }) => Promise<BatchCollectionDossierResponse>;
}
export class MarketplaceQueryClient implements MarketplaceReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.ask = this.ask.bind(this);
    this.getAllAsks = this.getAllAsks.bind(this);
    this.getSellerAsks = this.getSellerAsks.bind(this);
    this.getCollectionAsks = this.getCollectionAsks.bind(this);
    this.getCollectionVolume = this.getCollectionVolume.bind(this);
    this.collectionDossier = this.collectionDossier.bind(this);
    this.batchCollectionDossier = this.batchCollectionDossier.bind(this);
  }

  ask = async ({
    collection,
    tokenId
  }: {
    collection: string;
    tokenId: string;
  }): Promise<AskResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      ask: {
        collection,
        token_id: tokenId
      }
    });
  };
  getAllAsks = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: Uint64;
  }): Promise<GetAllAsksResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_all_asks: {
        limit,
        start_after: startAfter
      }
    });
  };
  getSellerAsks = async ({
    seller
  }: {
    seller: string;
  }): Promise<GetSellerAsksResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_seller_asks: {
        seller
      }
    });
  };
  getCollectionAsks = async ({
    collection
  }: {
    collection: string;
  }): Promise<GetCollectionAsksResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_collection_asks: {
        collection
      }
    });
  };
  getCollectionVolume = async ({
    collection
  }: {
    collection: string;
  }): Promise<GetCollectionVolumeResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_collection_volume: {
        collection
      }
    });
  };
  collectionDossier = async ({
    collection
  }: {
    collection: string;
  }): Promise<CollectionDossierResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      collection_dossier: {
        collection
      }
    });
  };
  batchCollectionDossier = async ({
    collections
  }: {
    collections: string[];
  }): Promise<BatchCollectionDossierResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      batch_collection_dossier: {
        collections
      }
    });
  };
}
export interface MarketplaceInterface extends MarketplaceReadOnlyInterface {
  contractAddress: string;
  sender: string;
  receive: ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  receiveNft: ({
    msg,
    sender,
    tokenId
  }: {
    msg: Binary;
    sender: string;
    tokenId: string;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  purchaseNative: ({
    collection,
    tokenId
  }: {
    collection: string;
    tokenId: string;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  removeListing: ({
    collection,
    tokenId
  }: {
    collection: string;
    tokenId: string;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  editAdminFee: ({
    newFee
  }: {
    newFee: Fee;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  editCreditContract: ({
    newContract
  }: {
    newContract: string;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
export class MarketplaceClient extends MarketplaceQueryClient implements MarketplaceInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.receive = this.receive.bind(this);
    this.receiveNft = this.receiveNft.bind(this);
    this.purchaseNative = this.purchaseNative.bind(this);
    this.removeListing = this.removeListing.bind(this);
    this.editAdminFee = this.editAdminFee.bind(this);
    this.editCreditContract = this.editCreditContract.bind(this);
  }

  receive = async ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive: {
        amount,
        msg,
        sender
      }
    }, fee, memo, funds);
  };
  receiveNft = async ({
    msg,
    sender,
    tokenId
  }: {
    msg: Binary;
    sender: string;
    tokenId: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive_nft: {
        msg,
        sender,
        token_id: tokenId
      }
    }, fee, memo, funds);
  };
  purchaseNative = async ({
    collection,
    tokenId
  }: {
    collection: string;
    tokenId: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      purchase_native: {
        collection,
        token_id: tokenId
      }
    }, fee, memo, funds);
  };
  removeListing = async ({
    collection,
    tokenId
  }: {
    collection: string;
    tokenId: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      remove_listing: {
        collection,
        token_id: tokenId
      }
    }, fee, memo, funds);
  };
  editAdminFee = async ({
    newFee
  }: {
    newFee: Fee;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      edit_admin_fee: {
        new_fee: newFee
      }
    }, fee, memo, funds);
  };
  editCreditContract = async ({
    newContract
  }: {
    newContract: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      edit_credit_contract: {
        new_contract: newContract
      }
    }, fee, memo, funds);
  };
}