/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.27.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type ExecuteMsg = {
  set_launch_time: {
    launch_time?: Timestamp | null;
    whitelist_launch_time?: Timestamp | null;
  };
} | {
  preload_data: {
    new_data: Metadata[];
  };
} | {
  receive: Cw20ReceiveMsg;
} | {
  nois_receive: {
    callback: NoisCallback;
  };
};
export type Timestamp = Uint64;
export type Uint64 = string;
export type Uint128 = string;
export type Binary = string;
export type HexBinary = string;
export interface Metadata {
  animation_url?: string | null;
  attributes?: Trait[] | null;
  background_color?: string | null;
  description?: string | null;
  external_url?: string | null;
  image?: string | null;
  image_data?: string | null;
  name?: string | null;
  youtube_url?: string | null;
}
export interface Trait {
  display_type?: string | null;
  trait_type: string;
  value: string;
}
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
  [k: string]: unknown;
}
export interface NoisCallback {
  job_id: string;
  published: Timestamp;
  randomness: HexBinary;
}
export type Addr = string;
export interface InstantiateMsg {
  admin: Addr;
  admin_fee: Fee;
  contract_name: string;
  contract_version: string;
  credit_contract: string;
  launch_time?: Timestamp | null;
  mint_price: Payment;
  nft_code_id: number;
  nft_symbol: string;
  nois_proxy: string;
  whitelist_launch_time?: Timestamp | null;
  whitelisted?: string[] | null;
}
export interface Fee {
  decimal_places: number;
  rate: number;
  recipient: string;
  [k: string]: unknown;
}
export interface Payment {
  amount: Uint128;
  token: Addr;
  [k: string]: unknown;
}
export type QueryMsg = {
  get_price: {};
} | {
  get_mint_status: {};
};
export interface MintStatus {
  launch_time?: Timestamp | null;
  remaining: number;
  whitelist_launch_time?: Timestamp | null;
  [k: string]: unknown;
}