/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.27.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type ExecuteMsg = {
  edit_admin: {
    new_admin: Addr;
  };
} | {
  edit_credit_permissions: {
    add_perms: boolean;
    address: Addr;
  };
} | {
  edit_operator_permissions: {
    add_perms: boolean;
    address: Addr;
  };
} | {
  edit_credit_rewards: {
    new_rewards: Config;
  };
} | {
  earn_credits: {
    msg?: Binary | null;
    sender: Addr;
  };
};
export type Addr = string;
export type Uint128 = string;
export type Binary = string;
export interface Config {
  alter_reward: Uint128;
  bid_reward: Uint128;
  buy_reward: Uint128;
  create_dao_reward: Uint128;
  feedback_reward: Uint128;
  mint_reward: Uint128;
  sell_reward: Uint128;
  vote_reward: Uint128;
  win_reward: Uint128;
  [k: string]: unknown;
}
export interface InstantiateMsg {
  admin: Addr;
  rewards: Config;
}
export type QueryMsg = {
  check_admin: {};
} | {
  check_balance: {
    user: Addr;
  };
} | {
  check_permission: {
    contract: Addr;
  };
} | {
  permissioned_contracts: {};
} | {
  check_stats: {};
};
export type Boolean = boolean;
export interface Stats {
  outstanding: Uint128;
  total_issued: Uint128;
  [k: string]: unknown;
}
export type ArrayOfAddr = Addr[];