/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.27.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { ExecuteMsg, Addr, Uint64, Payment, Uint128, Metadata, Trait, Fee, InstantiateMsg, QueryMsg, GetMintersResponse, Minter, GetNoisProxyResponse, ArrayOfMinter } from "./Factory.types";
export interface FactoryReadOnlyInterface {
  contractAddress: string;
  getMinters: () => Promise<GetMintersResponse>;
  getNoisProxy: () => Promise<GetNoisProxyResponse>;
}
export class FactoryQueryClient implements FactoryReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.getMinters = this.getMinters.bind(this);
    this.getNoisProxy = this.getNoisProxy.bind(this);
  }

  getMinters = async (): Promise<GetMintersResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_minters: {}
    });
  };
  getNoisProxy = async (): Promise<GetNoisProxyResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_nois_proxy: {}
    });
  };
}
export interface FactoryInterface extends FactoryReadOnlyInterface {
  contractAddress: string;
  sender: string;
  initRandomProject: ({
    beneficiary,
    collectionAdmin,
    contractName,
    label,
    launchTime,
    mintLimit,
    mintPrice,
    nftSymbol,
    rewardAdmin,
    whitelistLaunchTime,
    whitelisted,
    wlMintPrice
  }: {
    beneficiary: Addr;
    collectionAdmin: Addr;
    contractName: string;
    label: string;
    launchTime?: Uint64;
    mintLimit?: number;
    mintPrice: Payment;
    nftSymbol: string;
    rewardAdmin: string;
    whitelistLaunchTime?: Uint64;
    whitelisted?: string[];
    wlMintPrice?: Payment;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  initCopyProject: ({
    beneficiary,
    endTime,
    launchTime,
    maximumCopies,
    metadata,
    mintLimit,
    mintPrice,
    minterAdmin,
    minterLabel,
    nftAdmin,
    nftLabel,
    nftName,
    nftSymbol,
    whitelistLaunchTime,
    whitelistMintPrice,
    whitelisted
  }: {
    beneficiary: Addr;
    endTime?: Uint64;
    launchTime?: Uint64;
    maximumCopies?: number;
    metadata: Metadata;
    mintLimit?: number;
    mintPrice?: Payment;
    minterAdmin: Addr;
    minterLabel: string;
    nftAdmin: Addr;
    nftLabel: string;
    nftName: string;
    nftSymbol: string;
    whitelistLaunchTime?: Uint64;
    whitelistMintPrice?: Payment;
    whitelisted?: string[];
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  changeAdmin: ({
    newAdmin
  }: {
    newAdmin: string;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  changeFees: ({
    newFees
  }: {
    newFees: Fee;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  changeNoisProxy: ({
    newProxy
  }: {
    newProxy: string;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
export class FactoryClient extends FactoryQueryClient implements FactoryInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.initRandomProject = this.initRandomProject.bind(this);
    this.initCopyProject = this.initCopyProject.bind(this);
    this.changeAdmin = this.changeAdmin.bind(this);
    this.changeFees = this.changeFees.bind(this);
    this.changeNoisProxy = this.changeNoisProxy.bind(this);
  }

  initRandomProject = async ({
    beneficiary,
    collectionAdmin,
    contractName,
    label,
    launchTime,
    mintLimit,
    mintPrice,
    nftSymbol,
    rewardAdmin,
    whitelistLaunchTime,
    whitelisted,
    wlMintPrice
  }: {
    beneficiary: Addr;
    collectionAdmin: Addr;
    contractName: string;
    label: string;
    launchTime?: Uint64;
    mintLimit?: number;
    mintPrice: Payment;
    nftSymbol: string;
    rewardAdmin: string;
    whitelistLaunchTime?: Uint64;
    whitelisted?: string[];
    wlMintPrice?: Payment;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      init_random_project: {
        beneficiary,
        collection_admin: collectionAdmin,
        contract_name: contractName,
        label,
        launch_time: launchTime,
        mint_limit: mintLimit,
        mint_price: mintPrice,
        nft_symbol: nftSymbol,
        reward_admin: rewardAdmin,
        whitelist_launch_time: whitelistLaunchTime,
        whitelisted,
        wl_mint_price: wlMintPrice
      }
    }, fee, memo, funds);
  };
  initCopyProject = async ({
    beneficiary,
    endTime,
    launchTime,
    maximumCopies,
    metadata,
    mintLimit,
    mintPrice,
    minterAdmin,
    minterLabel,
    nftAdmin,
    nftLabel,
    nftName,
    nftSymbol,
    whitelistLaunchTime,
    whitelistMintPrice,
    whitelisted
  }: {
    beneficiary: Addr;
    endTime?: Uint64;
    launchTime?: Uint64;
    maximumCopies?: number;
    metadata: Metadata;
    mintLimit?: number;
    mintPrice?: Payment;
    minterAdmin: Addr;
    minterLabel: string;
    nftAdmin: Addr;
    nftLabel: string;
    nftName: string;
    nftSymbol: string;
    whitelistLaunchTime?: Uint64;
    whitelistMintPrice?: Payment;
    whitelisted?: string[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      init_copy_project: {
        beneficiary,
        end_time: endTime,
        launch_time: launchTime,
        maximum_copies: maximumCopies,
        metadata,
        mint_limit: mintLimit,
        mint_price: mintPrice,
        minter_admin: minterAdmin,
        minter_label: minterLabel,
        nft_admin: nftAdmin,
        nft_label: nftLabel,
        nft_name: nftName,
        nft_symbol: nftSymbol,
        whitelist_launch_time: whitelistLaunchTime,
        whitelist_mint_price: whitelistMintPrice,
        whitelisted
      }
    }, fee, memo, funds);
  };
  changeAdmin = async ({
    newAdmin
  }: {
    newAdmin: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      change_admin: {
        new_admin: newAdmin
      }
    }, fee, memo, funds);
  };
  changeFees = async ({
    newFees
  }: {
    newFees: Fee;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      change_fees: {
        new_fees: newFees
      }
    }, fee, memo, funds);
  };
  changeNoisProxy = async ({
    newProxy
  }: {
    newProxy: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      change_nois_proxy: {
        new_proxy: newProxy
      }
    }, fee, memo, funds);
  };
}