/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.27.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { ExecuteMsg, Addr, Timestamp, Uint64, Uint128, Payment, Fee, InstantiateMsg, QueryMsg } from "./Factory.types";
export interface FactoryReadOnlyInterface {
  contractAddress: string;
}
export class FactoryQueryClient implements FactoryReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
  }

}
export interface FactoryInterface extends FactoryReadOnlyInterface {
  contractAddress: string;
  sender: string;
  initProject: ({
    collectionAdmin,
    contractName,
    label,
    launchTime,
    mintPrice,
    nftSymbol,
    whitelistLaunchTime,
    whitelisted
  }: {
    collectionAdmin: Addr;
    contractName: string;
    label: string;
    launchTime?: Timestamp;
    mintPrice: Payment;
    nftSymbol: string;
    whitelistLaunchTime?: Timestamp;
    whitelisted?: string[];
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  changeAdmin: ({
    newAdmin
  }: {
    newAdmin: string;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
  changeFees: ({
    newFees
  }: {
    newFees: Fee;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
export class FactoryClient extends FactoryQueryClient implements FactoryInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.initProject = this.initProject.bind(this);
    this.changeAdmin = this.changeAdmin.bind(this);
    this.changeFees = this.changeFees.bind(this);
  }

  initProject = async ({
    collectionAdmin,
    contractName,
    label,
    launchTime,
    mintPrice,
    nftSymbol,
    whitelistLaunchTime,
    whitelisted
  }: {
    collectionAdmin: Addr;
    contractName: string;
    label: string;
    launchTime?: Timestamp;
    mintPrice: Payment;
    nftSymbol: string;
    whitelistLaunchTime?: Timestamp;
    whitelisted?: string[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      init_project: {
        collection_admin: collectionAdmin,
        contract_name: contractName,
        label,
        launch_time: launchTime,
        mint_price: mintPrice,
        nft_symbol: nftSymbol,
        whitelist_launch_time: whitelistLaunchTime,
        whitelisted
      }
    }, fee, memo, funds);
  };
  changeAdmin = async ({
    newAdmin
  }: {
    newAdmin: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      change_admin: {
        new_admin: newAdmin
      }
    }, fee, memo, funds);
  };
  changeFees = async ({
    newFees
  }: {
    newFees: Fee;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      change_fees: {
        new_fees: newFees
      }
    }, fee, memo, funds);
  };
}