/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.27.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type ExecuteMsg = {
  init_random_project: {
    beneficiary: Addr;
    collection_admin: Addr;
    contract_name: string;
    label: string;
    launch_time: Uint64;
    mint_limit?: number | null;
    mint_price: Payment;
    nft_symbol: string;
    reward_admin: string;
    whitelist_launch_time?: Uint64 | null;
    whitelisted?: string[] | null;
    wl_mint_price?: Payment | null;
  };
} | {
  init_copy_project: {
    beneficiary: Addr;
    end_time?: Uint64 | null;
    launch_time?: Uint64 | null;
    max_copies?: number | null;
    metadata: Metadata;
    mint_limit?: number | null;
    mint_price?: Payment | null;
    minter_admin: Addr;
    minter_label: string;
    nft_admin: Addr;
    nft_label: string;
    nft_name: string;
    nft_symbol: string;
    whitelist_launch_time?: Uint64 | null;
    whitelist_mint_price?: Payment | null;
    whitelisted?: string[] | null;
  };
} | {
  change_admin: {
    new_admin: string;
  };
} | {
  change_fees: {
    new_fees: Fee;
  };
} | {
  change_nois_proxy: {
    new_proxy: string;
  };
} | {
  change_random_code: {
    new_code: Uint64;
  };
} | {
  change_copy_code: {
    new_code: Uint64;
  };
} | {
  migrate_minter: {
    migrate_msg: Binary;
    minter_address: string;
    new_code_id: Uint64;
  };
} | {
  set_minter_premium: {
    minter_address: string;
    new_fee: Coin;
  };
};
export type Addr = string;
export type Uint64 = string;
export type Payment = {
  cw20_payment: {
    amount: Uint128;
    token: Addr;
    [k: string]: unknown;
  };
} | {
  native_payment: {
    amount: Uint128;
    denom: string;
    [k: string]: unknown;
  };
};
export type Uint128 = string;
export type Binary = string;
export interface Metadata {
  animation_url?: string | null;
  attributes?: Trait[] | null;
  background_color?: string | null;
  description?: string | null;
  external_url?: string | null;
  image?: string | null;
  image_data?: string | null;
  name?: string | null;
  royalty_payment_address?: string | null;
  royalty_percentage?: number | null;
  youtube_url?: string | null;
}
export interface Trait {
  display_type?: string | null;
  trait_type: string;
  value: string;
}
export interface Fee {
  decimal_places: number;
  rate: number;
  recipient: string;
  [k: string]: unknown;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export interface InstantiateMsg {
  admin: string;
  admin_fee: Fee;
  copy_mint_code_id: Uint64;
  credit_contract_addr: string;
  nft_contract_code_id: Uint64;
  nois_proxy: string;
  random_mint_code_id: Uint64;
  reward_recipient: string;
}
export type QueryMsg = {
  get_minters: {};
} | {
  get_nois_proxy: {};
};
export interface GetMintersResponse {
  minters: Minter[];
}
export interface Minter {
  minter_address: string;
  [k: string]: unknown;
}
export interface GetNoisProxyResponse {
  nois_proxy: string;
}
export type ArrayOfMinter = Minter[];