/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.27.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type ExecuteMsg = {
  init_project: {
    collection_admin: Addr;
    contract_name: string;
    label: string;
    launch_time?: Timestamp | null;
    mint_price: Payment;
    nft_symbol: string;
    whitelist_launch_time?: Timestamp | null;
    whitelisted?: string[] | null;
  };
} | {
  change_admin: {
    new_admin: string;
  };
} | {
  change_fees: {
    new_fees: Fee;
  };
};
export type Addr = string;
export type Timestamp = Uint64;
export type Uint64 = string;
export type Uint128 = string;
export interface Payment {
  amount: Uint128;
  token: Addr;
  [k: string]: unknown;
}
export interface Fee {
  decimal_places: number;
  rate: number;
  recipient: string;
  [k: string]: unknown;
}
export interface InstantiateMsg {
  admin: string;
  admin_fee: Fee;
  credit_contract_addr: string;
  nft_contract_code_id: number;
  nois_proxy: string;
  random_mint_code_id: number;
}
export type QueryMsg = string;